name: Python package

on:
  push:
    branches: [setup/flow]
  pull_request:
    branches: [dev, master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement-dev.txt
          pip install -e .

      # - uses: actions/checkout@v1
      # - name: Changelog check
      #   uses: Zomzog/changelog-checker@v1.2.0
      #   with:
      #     fileName: CHANGELOG.md
      #     checkNotification: Simple # default `Detailed`
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9"]

    steps:
      - name: Release PyPi
        run: |
        python setup.py bdist_wheel --universal
        twine upload -r pypihosted --verbose --config-file $(PYPIRC_PATH) dist/*.whl
